### ISSUE TITLE
npm version 2.0.0 not working - missing lib directory

### ISSUE THREAD

**Issue by ronen-e** [jokeyrhyme/is-dom4-supported#3]
version 2.0.0 is failing.
The main entry file has the lines
```
import { addSummary, assign } from './lib/helpers';
```
I see the `lib` directory in the repository,
but it is missing from the version published to npm.

**Comment by jokeyrhyme** [comment]
Ah, okay. Good catch.

It might be possible to import "is-dom4-supported/dist" or "is-dom4-supported/dist/index.js" for the time being. That should work whilst I fix up the missing files.

**Comment by jokeyrhyme** [comment]
I've published 2.0.1 to npm:
- https://github.com/jokeyrhyme/is-dom4-supported/releases/tag/2.0.1
- https://www.npmjs.com/package/is-dom4-supported
